site_name: Anything Minecraft
site_url: https://anythingmc.xyz/
repo_url: https://github.com/Anything-Minecraft-Team/anything-minecraft
edit_uri: tree/main/docs

theme:
  name: material
  favicon: https://media.discordapp.net/attachments/837476686978482207/848859250489819156/Untitled.png?width=170
  features:
    - content.code.annotate
  palette:
    - scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

extra_javascript:
  - js/arcio.js

markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - meta
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - toc:
      permalink: true
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
