---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
  labels:
    app: minecraft-server
    designation: server

spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
      designation: server
  template:
    metadata:
      namespace: minecraft-server
      annotations:
        backup.velero.io/backup-volumes: minecraft-server-persistent-storage
      labels:
        app: minecraft-server
        designation: server
    spec:
      containers:
        - name: minecraft-server
          image: itzg/minecraft-server:adopt11
          imagePullPolicy: Always
          env:
            - name: EULA
              value: "TRUE"
            - name: SERVER_NAME
              value: Minecraft Bonanza
            - name: TYPE
              value: PAPER
            - name: ENABLE_COMMAND_BLOCK
              value: "TRUE"
            - name: ENABLE_RCON
              value: "TRUE"
            - name: INIT_MEMORY
              value: 1G
            - name: MAX_MEMORY
              value: 3G
            - name: RCON_PORT
              value: "25575"
            - name: RCON_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minecraft-server-env
                  key: RCON_PASSWORD
          ports:
            - name: join
              containerPort: 25565
          volumeMounts:
            - name: minecraft-server-persistent-storage
              mountPath: /data
      volumes:
        - name: minecraft-server-persistent-storage
          persistentVolumeClaim:
            claimName: minecraft-server-pv-claim
