---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-server-service
  namespace: minecraft-server
  labels:
    name: minecraft-server
    designation: server
spec:
  # You can add an external IP here or use a proxy ingress. See k3s-proxy folder.
  #externalIPs:
  # - xx.xx.xx.xx
  ports:
    - port: 25565
      name: join
      targetPort: join
      protocol: TCP
  selector:
    app: minecraft-server
    designation: server
