---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-server-pv-claim
  namespace: minecraft-server
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20G
