---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minecraft-server

resources:
  - base/01-namespace.yml
  - base/02-pvc-config.yml
  - server/01-deployment.yml
  - server/02-join-service.yml

secretGenerator:
  - name: minecraft-server-env
    # env is a path to a file to read lines of key=val
    # you can only specify one env file per secret.
    env: secrets/env.txt
    type: Opaque
